# Generated by Django 5.1.3 on 2024-12-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_producto_informacion_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='dimensiones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='products.dimensiones'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
