# Generated by Django 5.1.4 on 2024-12-04 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_reseña_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='products.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Reseña',
        ),
    ]
